vich_uploader:
    db_driver: orm

    mappings:
        user_image:
            uri_prefix: /images/user_image
            upload_destination: '%kernel.project_dir%/public/images/user_image'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
