<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.D0YRnqg' shared service.

return $this->privates['.service_locator.D0YRnqg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\PartenaireController::ajoutcompt' => ['privates', '.service_locator.xHj_yg.', 'get_ServiceLocator_XHjYg_Service.php', true],
    'App\\Controller\\PartenaireController::depot' => ['privates', '.service_locator.9V_Ytlz', 'get_ServiceLocator_9VYtlzService.php', true],
    'App\\Controller\\PartenaireController::partBloquer' => ['privates', '.service_locator.n980HX4', 'get_ServiceLocator_N980HX4Service.php', true],
    'App\\Controller\\SecurityController::ajoutpart' => ['privates', '.service_locator.2B8PUum', 'get_ServiceLocator_2B8PUumService.php', true],
    'App\\Controller\\SecurityController::ajoutpartuser' => ['privates', '.service_locator.2B8PUum', 'get_ServiceLocator_2B8PUumService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.0xDS.HG', 'get_ServiceLocator_0xDS_HGService.php', true],
    'App\\Controller\\SecurityController::register' => ['privates', '.service_locator.2B8PUum', 'get_ServiceLocator_2B8PUumService.php', true],
    'App\\Controller\\SecurityController::userBloquer' => ['privates', '.service_locator.U2OyWts', 'get_ServiceLocator_U2OyWtsService.php', true],
    'App\\Controller\\PartenaireController:ajoutcompt' => ['privates', '.service_locator.xHj_yg.', 'get_ServiceLocator_XHjYg_Service.php', true],
    'App\\Controller\\PartenaireController:depot' => ['privates', '.service_locator.9V_Ytlz', 'get_ServiceLocator_9VYtlzService.php', true],
    'App\\Controller\\PartenaireController:partBloquer' => ['privates', '.service_locator.n980HX4', 'get_ServiceLocator_N980HX4Service.php', true],
    'App\\Controller\\SecurityController:ajoutpart' => ['privates', '.service_locator.2B8PUum', 'get_ServiceLocator_2B8PUumService.php', true],
    'App\\Controller\\SecurityController:ajoutpartuser' => ['privates', '.service_locator.2B8PUum', 'get_ServiceLocator_2B8PUumService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.0xDS.HG', 'get_ServiceLocator_0xDS_HGService.php', true],
    'App\\Controller\\SecurityController:register' => ['privates', '.service_locator.2B8PUum', 'get_ServiceLocator_2B8PUumService.php', true],
    'App\\Controller\\SecurityController:userBloquer' => ['privates', '.service_locator.U2OyWts', 'get_ServiceLocator_U2OyWtsService.php', true],
], [
    'App\\Controller\\PartenaireController::ajoutcompt' => '?',
    'App\\Controller\\PartenaireController::depot' => '?',
    'App\\Controller\\PartenaireController::partBloquer' => '?',
    'App\\Controller\\SecurityController::ajoutpart' => '?',
    'App\\Controller\\SecurityController::ajoutpartuser' => '?',
    'App\\Controller\\SecurityController::login' => '?',
    'App\\Controller\\SecurityController::register' => '?',
    'App\\Controller\\SecurityController::userBloquer' => '?',
    'App\\Controller\\PartenaireController:ajoutcompt' => '?',
    'App\\Controller\\PartenaireController:depot' => '?',
    'App\\Controller\\PartenaireController:partBloquer' => '?',
    'App\\Controller\\SecurityController:ajoutpart' => '?',
    'App\\Controller\\SecurityController:ajoutpartuser' => '?',
    'App\\Controller\\SecurityController:login' => '?',
    'App\\Controller\\SecurityController:register' => '?',
    'App\\Controller\\SecurityController:userBloquer' => '?',
]);
