<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLXb19Io\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLXb19Io/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLXb19Io.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLXb19Io\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLXb19Io\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LXb19Io',
    'container.build_id' => '847ef9f3',
    'container.build_time' => 1565967477,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLXb19Io');
