<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYwsEjrr\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYwsEjrr/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYwsEjrr.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYwsEjrr\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYwsEjrr\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YwsEjrr',
    'container.build_id' => '7a507a3a',
    'container.build_time' => 1567637297,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYwsEjrr');
