<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDjIsnxu\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDjIsnxu/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDjIsnxu.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDjIsnxu\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDjIsnxu\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'DjIsnxu',
    'container.build_id' => '4f27f11f',
    'container.build_time' => 1565981184,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDjIsnxu');
