<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.lT3owaF' shared service.

return $this->privates['.service_locator.lT3owaF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\PartenaireController::ajoutcompt' => ['privates', '.service_locator.xHj_yg.', 'get_ServiceLocator_XHjYg_Service.php', true],
    'App\\Controller\\SecurityController::ajoutpart' => ['privates', '.service_locator.2B8PUum', 'get_ServiceLocator_2B8PUumService.php', true],
    'App\\Controller\\SecurityController::ajoutpartuser' => ['privates', '.service_locator.2B8PUum', 'get_ServiceLocator_2B8PUumService.php', true],
    'App\\Controller\\SecurityController::register' => ['privates', '.service_locator.2B8PUum', 'get_ServiceLocator_2B8PUumService.php', true],
    'App\\Controller\\PartenaireController:ajoutcompt' => ['privates', '.service_locator.xHj_yg.', 'get_ServiceLocator_XHjYg_Service.php', true],
    'App\\Controller\\SecurityController:ajoutpart' => ['privates', '.service_locator.2B8PUum', 'get_ServiceLocator_2B8PUumService.php', true],
    'App\\Controller\\SecurityController:ajoutpartuser' => ['privates', '.service_locator.2B8PUum', 'get_ServiceLocator_2B8PUumService.php', true],
    'App\\Controller\\SecurityController:register' => ['privates', '.service_locator.2B8PUum', 'get_ServiceLocator_2B8PUumService.php', true],
], [
    'App\\Controller\\PartenaireController::ajoutcompt' => '?',
    'App\\Controller\\SecurityController::ajoutpart' => '?',
    'App\\Controller\\SecurityController::ajoutpartuser' => '?',
    'App\\Controller\\SecurityController::register' => '?',
    'App\\Controller\\PartenaireController:ajoutcompt' => '?',
    'App\\Controller\\SecurityController:ajoutpart' => '?',
    'App\\Controller\\SecurityController:ajoutpartuser' => '?',
    'App\\Controller\\SecurityController:register' => '?',
]);
